add bond export/import feature
go-bond/bond pull request #117
Opened 2023-11-13 09:25 UTC by poonai

2023-11-14 10:06 UTC, marino39 requested changes

2023-11-14 10:06 UTC, marino39 commented on backup.go
> +func (t *_table[T]) insertSST(ctx context.Context, path string) error {
Please consider using more descriptive names e.g. insertFromSST

2023-11-14 10:06 UTC, marino39 commented on backup.go
> +		if err := t.Insert(ctx, entries, batch); err != nil {
If you are using Table.Insert then indexes will be updated by it. It's better to use t.db.Set. It will give you flexibility to have indexes in the backup or not.

2023-11-14 10:06 UTC, marino39 commented on backup.go
> +	case ingestSST:
Which one of those works better? I guess ingest.

2023-11-14 10:06 UTC, marino39 commented on backup.go
> +func IteratorToSST(itr Iterator, path string) error {
This probably should be private.

2023-11-14 10:06 UTC, marino39 commented on bond.go
> +	Backup(ctx context.Context, dir string, index bool, tables ...tableBackup) error
Can we have Dump & Restore?

2023-11-14 10:06 UTC, marino39 commented on backup.go
> +package bond
The command line tool remains to be done.

2023-11-14 12:31 UTC, poonai commented on backup.go
> +		if err := t.Insert(ctx, entries, batch); err != nil {
It'll be used if the KV layout changes. Otherwise, direct SST ingestion will be used.

2023-11-14 12:32 UTC, poonai commented on backup.go
> +	case ingestSST:
yes, strategy is decided based on `BOND_DATA_VERSION`

2023-11-14 12:38 UTC, poonai commented on backup.go
> +package bond
`batchedInsert` strategy needs `Table` struct to do the restore. Since the schema is provided via `Table` struct. 

So, I've made the API for the end user to build the tool according to their need.

2023-11-14 12:59 UTC, marino39 commented on backup.go
> +	case ingestSST:
probably we should also version schema

2023-11-14 15:18 UTC, marino39 commented on backup.go
> +package bond
Hmmm, to be honest, we do not really care what the data is. Not sure if we even should use ```Table```.

We could just copy keys / data. You know key ranges for data and key ranges for indexes. We also should have schema version somewhere so we do not have schema mismatches.

2023-11-15 04:45 UTC, poonai commented on backup.go
> +	case ingestSST:
yes, that's been added https://github.com/go-bond/bond/pull/117/files#diff-0b38a3f2c61dc1e8795a945dd3d1fcf7939c85b7415954659de868412c49b533R322

2023-11-16 09:29 UTC, marino39 commented on bond.go
> +func (db *_db) Dump(_ context.Context, path string, index bool) error {
index -> withIndex

2023-11-16 09:32 UTC, marino39 commented on cmd/bond-cli/bond-cli.go
> +			inspect.NewInspectCLI(nil),
Have you checked if inspect still works after making changes?

2023-11-16 09:33 UTC, marino39 commented on index.go
> -
Why we made those changes?

2023-11-16 09:34 UTC, marino39 commented on cmd/bond-cli/dump.go
> +	Name:     "index",
with-indexes

2023-11-16 09:37 UTC, marino39 commented on bond.go
> +	Dump(ctx context.Context, dir string, index bool) error
Can we also have DumpTables(ctx context.Context, dir string, tables []TableID, withIndexes bool)?

Sorry for this addition however this is a thing that Shub needs.

2023-11-17 07:07 UTC, poonai commented on cmd/bond-cli/bond-cli.go
> +			inspect.NewInspectCLI(nil),
yes

2023-11-17 11:59 UTC, merged