add pebble version check
go-bond/bond pull request #127
Opened 2024-02-19 05:21 UTC by poonai

2024-02-19 08:06 UTC, marino39 requested changes
One small comment otherwise it LGTM.

2024-02-19 08:06 UTC, marino39 commented on bond.go
> +	_, err := os.Stat(dirname)
Please use the path ``path.Join(dirname, "bond")``. We had issues before with storing files along sstables. It's safer to have additional files in subdir.

2024-02-19 08:09 UTC, marino39 commented on bond.go
> +	_, err := os.Stat(dirname)
Or maybe put sstables in subdir WDYT?

```
bond/pebble
bond/PEBBLE_FORMAT_VERSION
```

2024-02-19 11:18 UTC, marino39 approved these changes
One more minor comment, otherwise LGTM.

2024-02-19 11:18 UTC, marino39 commented on bond.go
> +	_, err := os.Stat(filepath.Join(dirname, "bond"))
Please consider assigning this to var instead of recalculating paths all the time.

2024-02-19 12:33 UTC, pkieltyka commented
very helpful.

what should we do in cases when we want for bond to proceed to open..?

2024-02-19 12:35 UTC, poonai commented
@pkieltyka we have migration framework planned for that. 

https://github.com/go-bond/bond/issues/126

2024-02-19 12:37 UTC, marino39 commented
BTW: @poonai I forgot that the ticket also mentioned implementing the pebble format migration mechanism. Please do that in this ticket too.

2024-02-20 09:32 UTC, marino39 approved these changes
Please apply one last comment and merge the PR.

2024-02-20 09:32 UTC, marino39 commented on bond.go
> +	pebbelVersionPath := filepath.Join(bondPath, "PEBBLE_FORMAT_VERSION")
Use const for ``bond`` and ``PEBBLE_FORMAT_VERSION``. It just makes any changes easier by just editing the const.

2024-02-20 09:57 UTC, merged