store bond db data version for new db, and check on open
go-bond/bond pull request #49
Opened 2022-08-19 01:12 UTC by pkieltyka

tests fail, but, is WIP

2022-08-19 01:25 UTC, pkieltyka commented
<img width="632" alt="image" src="https://user-images.githubusercontent.com/18831/185522083-5f459a02-618c-40d2-a4be-42401df12a9a.png">

I was reading the test cases using `it := db.NewIter(nil)` I think it would be cool to have..

```go
it := tokenBalanceTable.NewIter(nil)
for it.First(); it.Valid(); it.Next() {
  // .. iterate through the table keys
}
```

2022-08-19 08:43 UTC, marino39 commented
> <img alt="image" width="632" src="https://user-images.githubusercontent.com/18831/185522083-5f459a02-618c-40d2-a4be-42401df12a9a.png">
> 
> I was reading the test cases using `it := db.NewIter(nil)` I think it would be cool to have..
> 
> ```go
> it := tokenBalanceTable.NewIter(nil)
> for it.First(); it.Valid(); it.Next() {
>   // .. iterate through the table keys
> }
> ```

Sure, I will put it on my todo list.

2022-08-19 09:35 UTC, marino39 requested changes
Please see my comments :)

2022-08-19 09:35 UTC, marino39 commented on version.go
> +	BOND_DB_DATA_VERSION_KEY = "__bond_db_version__"
It will collide with Table that has id = 0x5F('_'). I would reserver tableID == 0x00 for internal go-bond storage.

```golang
table.go

const TableIDReserved = TableID(0)

db.go

const InternalStoragePrefix = string(byte(0))

version.go

const (
       // BOND_DB_DATA_VERSION ..
       BOND_DB_DATA_VERSION = 1

	// BOND_DB_DATA_VERSION_KEY ..
       BOND_DB_DATA_VERSION_KEY = InternalStoragePrefix + "__bond_db_version__"
)
```

2022-08-19 09:35 UTC, marino39 commented on version.go
> +	BOND_DB_DATA_VERSION = 1
I also used camelcase in all constants in go-bond. We need to stay consistent. So we either rename all constants or we define those in camelcase.

2022-08-19 09:35 UTC, marino39 commented on version.go
> +	return db.Set([]byte(BOND_DB_DATA_VERSION_KEY), []byte(ver), &pebble.WriteOptions{Sync: true})
The ```&pebble.WriteOptions{Sync: true}``` can be shortened ```pebble.Sync```.

2022-08-19 09:37 UTC, marino39 commented on version.go
> +	BOND_DB_DATA_VERSION_KEY = "__bond_db_version__"
We also could add a KeyType byte in front of the key this way we wouldn't need to have reserved TableID.

2022-08-21 20:17 UTC, pkieltyka commented on version.go
> +	BOND_DB_DATA_VERSION = 1
I prefer camel case for constants too, but for the "internal" constants, I prefer to use all caps so its really explicit / clear and should hopefully be avoided in normal use. I think the styles are compatible.

2022-08-21 20:18 UTC, pkieltyka commented on version.go
> +	BOND_DB_DATA_VERSION_KEY = "__bond_db_version__"
good point. I set 0x0 as the reserved table id for bond internal table. I think this is easiest / simplest / clean.

it just means if an app tries to use table id < 1 we should error

2022-08-21 20:19 UTC, pkieltyka commented
FYI, I implemented Table.NewIter(..) method in this PR as well, which fixes the tests

2022-08-21 20:19 UTC, merged