use pebble buffer to encode keys
go-bond/bond pull request #64
Opened 2022-11-23 04:43 UTC by poonai

Signed-off-by: poonai <rbalajis25@gmail.com>

2022-11-23 07:52 UTC, marino39 requested changes
Please see my comments.

2022-11-23 07:52 UTC, marino39 commented on bond.go
> +type Deferred interface {
Please call it DeferredSetter.

2022-11-23 07:52 UTC, marino39 commented on keys.go
> +func NewKeyBuilder(buff []byte, estimateSize bool) KeyBuilder {
Once ```estimateSize``` is true we do not build the key, please call it estimateSizeOnly and make it an optional argument. So it's not visible in most cases.

2022-11-23 07:52 UTC, marino39 commented on keys.go
> +		return bt.addSize(1 + bytesLen)
```putFieldID``` already increased size, so you don't need to add 1 in here

2022-11-23 07:52 UTC, marino39 commented on keys.go
> +		return bt.addSize(1 + 2)
same as below

2022-11-23 07:52 UTC, marino39 commented on keys.go
> +		return bt.addSize(1 + 4)
same as below

2022-11-23 07:52 UTC, marino39 commented on keys.go
> +		return bt.addSize(1 + 8)
same as below

2022-11-23 07:52 UTC, marino39 commented on keys_test.go
> +func TestKeyBuildSizeEstimation(t *testing.T) {
This test case must be wrong.

2022-11-23 07:52 UTC, marino39 commented on keys.go
> +func KeyEncodePebble(key KeyV2, rawBuf []byte) []byte {
I would rather have something like this in KeyBytes. Not sure what it would look like at the moment.

Maybe like this:
```golang
defSet := b.SetDeferred(EstimateKeySize(), EstimateDataSize())

KeyBytes(defSet.Key[:0]).
       EncodeTableID(t.ID).
       EncodeIndexID(idx.ID).
       EncodeIndexKey(encFunc func(KeyBytes) KeyBytes).
       EncodeIndexOrder(encFunc func(KeyBytes) KeyBytes).
       EncodePrimaryKey(encFunc func(KeyBytes) KeyBytes)
```

Above code would work like this:
1. ```defSet.Key``` is a bytes buffer of our estimated keySize
2. We create slice from that buffer that has lengths 0
3.  We encode stuff into it in proper order(functions may assert if they are executed properly)
4. The indexKey, indexOrder and primaryKey are encoded using callbacks that would encode stuff into it directly using ```KeyBuilder```

I'm not sure if KeySizeInfo is needed in that particular scenario.

2022-11-23 08:11 UTC, marino39 commented on keys.go
> +func KeyEncodePebble(key KeyV2, rawBuf []byte) []byte {
or

```golang
KeyBytes(defSet.Key[:0]).Encode(EncodeOptions{
    TableID: t.ID,
    IndexID: idx.ID,
    IndexKeyEncFunc: func (KeyBytes) KeyBytes {
    }
   IndexOrderEncFunc: func (KeyBytes) KeyBytes {
   } 
   PrimaryKeyEncFunc: func (KeyBytes) KeyBytes {
   } 
}
```

This way there is no risk that something will be executed out of order.

2022-11-30 04:26 UTC, poonai commented
Closing this because we were able to see only minimal difference. 

If needed this code can be brought back.

2022-11-30 04:26 UTC, closed without merging