POC: block collector
go-bond/bond pull request #70
Opened 2022-11-30 04:28 UTC by poonai

2022-11-30 09:34 UTC, marino39 commented on keys.go
> +func (key KeyBytes) PrimaryKey() []byte {
This is wrong as indexKey and indexOrder have variable length.

2022-11-30 09:34 UTC, marino39 commented on table.go
> +	opt := &IterOptions{
I would implement Get based on iterator with filter to see if it will be any faster.

2022-11-30 09:34 UTC, marino39 commented on collector.go
> +	return b.Encode(buf), nil
Please check if this is executed.

2022-11-30 09:34 UTC, marino39 commented on collector.go
> +func (*BlockCollector) FinishIndexBlock(buf []byte) ([]byte, error) {
We might want this properties in different type of blocks too.

2022-11-30 09:34 UTC, marino39 commented on collector.go
> +func (*BlockCollector) FinishTable(buf []byte) ([]byte, error) {
It could be useful here as well.

2022-12-13 18:05 UTC, marino39 requested changes

2022-12-13 18:05 UTC, marino39 commented on iter.go
> +func (b *BondIterator) Exist(key []byte) bool {
Please refactor and use _table.exist function instead this one.

2022-12-13 18:05 UTC, marino39 commented on options.go
> +	opts.FormatMajorVersion = pebble.FormatNewest
Please use fixed format constant. If we have pebble.FormatNewest we can trigger unexpected format upgrade. That may take couple of hours.

2022-12-13 18:05 UTC, marino39 commented on table.go
> +func (t *_table[T]) keys(trs []T) ([][]byte, bool, func()) {
Please move function to key related section of the file.

2022-12-13 18:05 UTC, marino39 commented on table.go
> +		keyBuffer := _keyBufferPool.Get().([]byte)
Please consider creating pool with big buffers and use that single buffer for all keys.

This will be more space efficient as there will be fewer unused parts of the buffer.

2022-12-13 18:05 UTC, marino39 commented on table.go
> +		if filter.Lookup(key) {
Not sure if we should check for duplicates here. I know that thanks to this we will return error earlier, however this is edge case that should never happen. So if once every now and then we do a little bit of work it will not hurt us.

tbh. I would remove it

2022-12-13 18:05 UTC, marino39 commented on table.go
> +		if itr.Exist(key) {
Please refactor and use _table.exist here.

2022-12-13 18:05 UTC, marino39 commented on table.go
> +	if !itr.SeekGE(key) {
itr.Seek and bytes.Equal can be checked in line

2022-12-13 18:05 UTC, marino39 commented on table.go
> +	data := itr.Value()
This can be passed directly to Deserialize.

2022-12-13 18:05 UTC, marino39 commented on utils/common.go
> +func Duplicate(arr [][]byte) (int, bool) {
Remove if not needed anymore.

2022-12-14 18:06 UTC, closed without merging

2022-12-14 18:06 UTC, pkieltyka commented
merged https://github.com/go-bond/bond/pull/78

great work @poonai and @marino39 :1st_place_medal: