use iterator for query execution
go-bond/bond pull request #83
Opened 2023-01-11 08:38 UTC by poonai

2023-01-11 14:36 UTC, marino39 requested changes

2023-01-11 14:36 UTC, marino39 commented on query.go
> +	var batchedKeys [][]byte
If we put optimization here users if they choose to use Table.Scan,... or Table.ForEach will still use inefficient implementation.

I would rather use indexIterator in Table itself. It would apply optimization across the board.

2023-01-11 14:36 UTC, marino39 commented on table.go
> +func (r *_indexIter[T]) Deserialize(val []byte) (T, error) {
Iterator shouldn't have Deserialization function. It's low level entity. You can get serializer from table.

2023-01-11 14:36 UTC, marino39 commented on table.go
> +func (t *_table[T]) indexIter(ctx context.Context, prefix []byte, optBatch ...Batch) (*_indexIter[T], bool) {
This is ok.

2023-01-11 14:36 UTC, marino39 commented on table.go
> +type _indexIter[T any] struct {
I would put indexIterator along in iter.go file.

2023-01-11 14:36 UTC, marino39 commented on query.go
> +	var batchedKeys [][]byte
If you would like we can do a pair programming session tomorrow.

2023-01-16 10:26 UTC, marino39 requested changes

2023-01-16 10:26 UTC, marino39 commented on table.go
> +	// reverts the keys to the original order.
I believe we should leave keys array as it is and have another array called keysOrdered that we use to get elements from the database. Then we use sort.Search to efficiently reorder records. We can use your method, however I'm not sure if that's going to be any faster.

BTW: This code does not return records in the same order as keys.

2023-01-16 10:26 UTC, marino39 commented on table.go
> +				cont, err := f(iter.Key(), Lazy[T]{getValueAndPrefetch})
I would rather have a separate function here called getValuePrefetched. Otherwise, the code gets harder to understand.

2023-01-16 10:26 UTC, marino39 commented on table.go
> +func (t *_table[T]) Deserialize(val []byte) (T, error) {
Is this function used anywhere?

2023-01-16 10:26 UTC, marino39 commented on table.go
> +				keys = append(keys, utils.Copy([]byte{}, KeyBytes(iter.Key()).ToDataKeyBytes(keyBuffer[:0])))
The allocs can be optimized here.

2023-01-16 10:26 UTC, marino39 commented on cmd/tools/immense_bench/main.go
> +var (
I have run our usual benchmarks. This is for some reason massively worse than the previous impl.

2023-01-19 05:12 UTC, poonai commented
benchmark results:

optimized branch:
```
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_0_Limit_0                                         1	21055937364 ns/op	         0.04749 op/s 3600063384 B/op	100200708 allocs/op
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_0_Limit_500                                    2287	    529177 ns/op	      1890 op/s           68586 B/op	    2519 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_0_Limit_1000                                   1082	   1043116 ns/op	       958.7 op/s        145901 B/op	    5026 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_0_Limit_5000                                    230	   5110192 ns/op	       195.7 op/s        729229 B/op	   25028 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_0_Limit_10000                                   100	  10406449 ns/op	        96.09 op/s      1560184 B/op	   50036 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_0_Limit_100000                                   10	 101328707 ns/op	         9.869 op/s    16119728 B/op	  500082 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_0_Limit_0                                         1	22315246452 ns/op	         0.04481 op/s 3596825168 B/op	100039939 allocs/op
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_500_Limit_1000                                 1041	   1082262 ns/op	       924.0 op/s        146058 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_1000_Limit_1000                                1046	   1156671 ns/op	       864.6 op/s        146088 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_5000_Limit_1000                                 704	   1703813 ns/op	       586.9 op/s        147076 B/op	    5033 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_10000_Limit_1000                                511	   2361835 ns/op	       423.4 op/s        145831 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_100000_Limit_1000                                78	  14403042 ns/op	        69.43 op/s       150355 B/op	    5032 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_1000000_Limit_1000                                8	 137239088 ns/op	         7.287 op/s      198083 B/op	    5155 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_0_Offset_10000000_Limit_1000                               1	1647326006 ns/op	         0.6070 op/s     195752 B/op	    5522 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_501_Offset_0_Limit_1000                                 1166	   1045399 ns/op	       956.6 op/s        145389 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_1001_Offset_0_Limit_1000                                1004	   1019938 ns/op	       980.5 op/s        145027 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_5001_Offset_0_Limit_1000                                1159	   1047076 ns/op	       955.0 op/s        145436 B/op	    5022 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_10001_Offset_0_Limit_1000                               1178	   1029620 ns/op	       971.2 op/s        145193 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_100001_Offset_0_Limit_1000                              1189	   1055724 ns/op	       947.2 op/s        145241 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_1000001_Offset_0_Limit_1000                             1182	   1058053 ns/op	       945.1 op/s        145455 B/op	    5027 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_Default_Sel_10000001_Offset_0_Limit_1000                            1173	   1044763 ns/op	       957.2 op/s        145232 B/op	    5021 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_0_Limit_0                                  1	38171359220 ns/op	         0.02620 op/s 9796115840 B/op	175980697 allocs/op
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_0_Limit_500                             1153	    992067 ns/op	      1008 op/s          253695 B/op	    4814 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_0_Limit_1000                             622	   1972188 ns/op	       507.1 op/s        521880 B/op	    9621 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_0_Limit_5000                             117	   9802515 ns/op	       102.0 op/s       2644635 B/op	   48065 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_0_Limit_10000                             60	  19515638 ns/op	        51.24 op/s      5393038 B/op	   96118 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_0_Limit_100000                             6	 195062979 ns/op	         5.127 op/s    54517332 B/op	  961032 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_0_Limit_0                                  1	38039144899 ns/op	         0.02629 op/s 9773919584 B/op	175807212 allocs/op
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_500_Limit_1000                           578	   2073426 ns/op	       482.3 op/s        633136 B/op	   10701 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_1000_Limit_1000                          552	   2176146 ns/op	       459.5 op/s        743181 B/op	   11781 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_5000_Limit_1000                          348	   3225207 ns/op	       310.1 op/s       1627674 B/op	   20421 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_10000_Limit_1000                         260	   4715054 ns/op	       212.1 op/s       2690211 B/op	   31221 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_100000_Limit_1000                         40	  28801651 ns/op	        34.72 op/s     22602926 B/op	  225622 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_1000000_Limit_1000                         4	 271108255 ns/op	         3.689 op/s    221473036 B/op	 2169635 allocs/op  
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_0_Offset_10000000_Limit_1000                        1	2862199355 ns/op	         0.3494 op/s   2194667872 B/op	21607785 allocs/op 
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_500_Offset_0_Limit_1000                           543	   1927094 ns/op	       518.9 op/s        525081 B/op	    9621 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_1000_Offset_0_Limit_1000                          610	   1953751 ns/op	       511.8 op/s        506183 B/op	    9621 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_5000_Offset_0_Limit_1000                          535	   1965669 ns/op	       508.7 op/s        525363 B/op	    9621 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_10000_Offset_0_Limit_1000                         553	   1962140 ns/op	       509.6 op/s        524739 B/op	    9621 allocs/op   
BenchmarkTableQuerySuite/CBORSerializer/Query_Index_AccountAddress_Sel_100000_Offset_0_Limit_1000                       [...]

2023-01-19 11:04 UTC, marino39 requested changes

2023-01-19 11:04 UTC, marino39 commented on table.go
> -		indexKeyBatch = t.db.Batch()
Why are we removing this? I would like to stay consistent with other functions.

2023-01-19 11:04 UTC, marino39 commented on table.go
> +	keyOrder := utils.ArrayN(len(keys))
You can use ```t.sortKeys()``` here.

2023-01-19 11:04 UTC, marino39 commented on table.go
> +	sort.Sort(&utils.SortShim{
You probably can have a separate restore original order func here.

2023-01-19 11:04 UTC, marino39 commented on table.go
> +		cont, err := f(iter.Key(), Lazy[T]{GetFunc: func() (T, error) {
It should pass primary index key here that contains data: ```KeyBytes(iter.Key()).ToDataKeyBytes(keyBuffer[:0])```

I know that it was wrong before.

2023-01-19 11:04 UTC, marino39 commented on table.go
> +			cont, err := f(t.indexKey(prefetchedBatch[prefetchedBatchIndex], idx, keyBuffer[:0]), Lazy[T]{GetFunc: func() (T, error) {
You just do ```keys[prefetchedBatchIndex]``` here.

2023-01-19 11:04 UTC, marino39 commented on table.go
> +			cont, err := f(t.indexKey(prefetchedBatch[prefetchedBatchIndex], idx, keyBuffer[:0]), Lazy[T]{GetFunc: func() (T, error) {
You shouldn't use the anonymous function here as it will get reallocated at each iteration. I propose adding ```getPrefetchedValue``` function above and just pass it here.

2023-01-19 11:04 UTC, marino39 commented on table_test.go
> +func TestScanIndexForEachSecondary(t *testing.T) {
Please use the same test naming convention as is used in this file e.g. ```TestBondTable_xyz```. It applies to all new tests.

2023-01-19 11:04 UTC, marino39 commented on table_test.go
> +			IndexOrderFunc: IndexOrderDefault[*TokenBalance],
Please use the custom order function here. Otherwise it's not really tested.

2023-01-19 11:04 UTC, marino39 commented on table_test.go
> +func TestTableScanPrimary(t *testing.T) {
This test is not necessary as PrmiaryIndex has only default ordering. So it will always match.

2023-01-20 09:42 UTC, marino39 approved these changes
LGTM

2023-01-20 09:43 UTC, merged